name: Reusable Python CI

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      python_version:
        required: false
        type: string
        default: "3.11"
      dockerfile:
        required: false
        type: string
        default: Dockerfile

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "IMAGE_TAG=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run Tests
        run: |
          pytest || echo "No tests"

      - name: Sonar Config
        run: |
          echo "sonar.projectKey=${GITHUB_REPOSITORY_OWNER}:${GITHUB_REPOSITORY##*/}" > sonar-project.properties
          echo "sonar.projectName=${GITHUB_REPOSITORY##*/}" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Prepare Docker Context
        run: |
          mkdir -p buildctx/backend/${{ inputs.service_name }}
          rsync -av --exclude buildctx ./ buildctx/
          rsync -av --exclude buildctx ./ buildctx/backend/${{ inputs.service_name }}/

      - name: Build Docker Image
        run: |
          docker build -f buildctx/Dockerfile \
          -t $IMAGE_NAME:$IMAGE_TAG buildctx

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG